application: cedarxy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*)
  static_files: \1
  upload: (.*)

error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html

  - error_code: dos_api_denial
    file: dos_api_denial.html

  - error_code: timeout
    file: timeout.html